# This is a basic workflow to help you get started with Actions

name: make-groups

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  make-group:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      members: ("김관경", "최용석", "이우재", "이선민", "임채윤", "김세영", "김건우", "신우성", "허준영", "권나영", "송민종", "이재권", "백수만", "이동재", "강보석", "박상준")
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: say hi
        run: echo "hi ${ env.members[0] }"!
